### ISSUE TITLE
[mystique] 运行脚本./run_batch_local_cifar10_101.sh报错

### ISSUE THREAD

**Issue by yjsunn** [LatticeX-Foundation/Rosetta#126]
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 106, in main
    cnn.build_model()
  File "/usr/wkspace/Rosetta/example/zkp_resnet/rtt-predict/ResNet.py", line 158, in build_model
    self.test_inptus, is_training=False, reuse=tf.AUTO_REUSE)
  File "/usr/wkspace/Rosetta/example/zkp_resnet/rtt-predict/ResNet.py", line 75, in network
    x = conv(x, channels=ch, kernel=3, stride=1, scope='conv')  # 32
  File "/usr/wkspace/Rosetta/example/zkp_resnet/rtt-predict/ops.py", line 25, in conv
    strides=stride, use_bias=use_bias, padding=padding, reuse=tf.AUTO_REUSE)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 424, in conv2d
    return layer.apply(inputs)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 586, in __call__
    self.name)
  File "/root/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/input_spec.py", line 111, in assert_input_compatibility
    layer_name + ' is incompatible with the layer: '
ValueError: Input 0 of layer conv2d_1 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

看起来这里像是resnet的input layer没有指定维度报错的，但是在第二步（2. Plaintext inference to verify the trained model）的时候可以正常输出明文下的推理结果

**Comment by yjsunn** [comment]
环境是ubuntu18.04, cmake version 3.10.2, pip 9.0.1, Python 3.6.9, tf version 1.14.0, keras 2.2.5. 根据https://github.com/LatticeX-Foundation/Rosetta/issues/114  , 打开shape inference 会报错segment fault（./run_batch_local_cifar10_101.sh: line 40: 44521 Segmentation fault      (core dumped) python3 main.py --phase test --dataset cifar10 --res_n 101 --lr 0.001 --input_public --epoch 1 --batch_size 1 --train_size 1 --test_size 1 --party_id=0 > log/cifar10-resnet101-input-public-0.log 2>&1），关上了之后会出现valueError的错误

**Comment by yjsunn** [comment]
the issue is solved after I upgrade to python3.7 with shape inference=ON
