### ISSUE TITLE
example中恢复模型错误

### ISSUE THREAD

**Issue by huajinghua** [LatticeX-Foundation/Rosetta#87]
1. 首先运行三方的rtt-logistic_regression_saver.py
2. 再运行rtt-logistic_regression_restore.py
3. 抛出异常
Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: tensor_name = b; expected dtype string does not equal original dtype double
tensor_name = w; expected dtype string does not equal original dtype double
	 [[{{node v2/SecureRestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/client/secure_session.py", line 79, in run
    return super().run(fetches, feed_dict, options, run_metadata)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: tensor_name = b; expected dtype string does not equal original dtype double
tensor_name = w; expected dtype string does not equal original dtype double
	 [[node v2/SecureRestoreV2 (defined at <string>:3992) ]]

Errors may have originated from an input operation.
Input Source operations connected to node v2/SecureRestoreV2:
 v2/Const (defined at /data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py:214)

Original stack trace for 'v2/SecureRestoreV2':
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jinghua/Documents/workspace/python/Rosetta/example/tutorials/code/rtt-logistic_regression_restore.py", line 49, in <module>
    saver = tf.train.Saver(var_list=None, max_to_keep=5, name='v2')
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 179, in __init__
    write_version, pad_step_number, save_relative_paths, filename)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 214, in _build
    build_restore=build_restore)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 122, in bulk_restore
    return SecureRestoreV2(filename_tensor, names, slices, dtypes)
  File "<string>", line 3992, in secure_restore_v2
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jinghua/Documents/workspace/python/Rosetta/example/tutorials/code/rtt-logistic_regression_restore.py", line 58, in <module>
    saver.restore(sess, './log/ckpt'+str(mpc_player_id)+'/model')
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1322, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

tensor_name = b; expected dtype string does not equal original dtype double
tensor_name = w; expected dtype string does not equal original dtype double
	 [[node v2/SecureRestoreV2 (defined at <string>:3992) ]]

Errors may have originated from an input operation.
Input Source operations connected to node v2/SecureRestoreV2:
 v2/Const (defined at /data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py:214)

Original stack trace for 'v2/SecureRestoreV2':
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jinghua/Documents/workspace/python/Rosetta/example/tutorials/code/rtt-logistic_regression_restore.py", line 49, in <module>
    saver = tf.train.Saver(var_list=None, max_to_keep=5, name='v2')
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 179, in __init__
    write_version, pad_step_number, save_relative_paths, filename)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 214, in _build
    build_restore=build_restore)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/data/projects/python/venv/lib/python3.7/site-packages/latticex/rosetta/secure/ops/training/io_saver.py", line 122, in bulk_restore
    return SecureRestoreV2(filename_tensor, names, slices, dtypes)
  File "<string>", line 3992, in secure_restore_v2
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/data/projects/python/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by xiaojiqing** [comment]
你这两个脚本修改了吗？

**Comment by xiaojiqing** [comment]
expected dtype string does not equal original dtype double这个错误的意思是saver_model是明文(double)，restore_model是密文(string)，saver_model和restore_model应该保持一致, set_saver_model(['P0']), set_restore_model('P0')这是从将明文保持到P0, 从P0加载明文

**Comment by huajinghua** [comment]
保存和恢复密文结果是怎么设置呢？将save_mode和restore_mode都设置成0对吗

**Comment by xiaojiqing** [comment]
密文是用字典设置的，rtt.set_saver_model({'P0':0, 'P1':1, 'P2':2})， key是node_id，需要保存密文的目标节点, value是party_id, 是密文的来源，计算节点本地保存密文可以写作rtt.set_saver_mode({})。rtt.set_restore_model({'P0':0, 'P1':1, 'P2':2})，key是node_id，模型来源，value是party_id，是接收模型的计算节点，计算节点本地加载密文可以写作rtt.set_restore_model({})。
